<a href="https://colab.research.google.com/github/surayaqis/Data-Science-Notes/blob/main/Chapter_5_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 5 - Numpy - Boolean Indexing

In [40]:
import numpy as np

In [41]:
names = np.array (['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [42]:
data = np.random.randn (7,4)
data

array([[ 1.40763989,  0.06948517, -1.27613851, -0.53275967],
       [ 0.10380487,  0.21498122,  0.67072755,  0.77321209],
       [-0.59152043, -0.46612442, -0.18010961,  0.18551973],
       [ 0.17564053, -0.63889051, -0.38270991,  0.12870264],
       [-1.46051822, -0.15296113, -0.85551065,  0.0689801 ],
       [-0.95997752,  0.16490724, -0.70213291, -0.12835829],
       [ 0.51764773, -1.65396676,  1.28771795,  1.04998571]])

In [43]:
names == 'Bob' #to check if names of row equals to Bob

array([ True, False, False,  True, False, False, False])

In [44]:
data[names=='Bob']  #akan keluarkan row Bob only

array([[ 1.40763989,  0.06948517, -1.27613851, -0.53275967],
       [ 0.17564053, -0.63889051, -0.38270991,  0.12870264]])

In [45]:
data[names=='Bob',2:]  #to call out column 2 onwards

array([[-1.27613851, -0.53275967],
       [-0.38270991,  0.12870264]])

In [46]:
names != 'Bob'   #check everything except Bob

array([False,  True,  True, False,  True,  True,  True])

In [47]:
data[~(names=='Bob')]   #select everything except Bob

array([[ 0.10380487,  0.21498122,  0.67072755,  0.77321209],
       [-0.59152043, -0.46612442, -0.18010961,  0.18551973],
       [-1.46051822, -0.15296113, -0.85551065,  0.0689801 ],
       [-0.95997752,  0.16490724, -0.70213291, -0.12835829],
       [ 0.51764773, -1.65396676,  1.28771795,  1.04998571]])

In [48]:
#to replace value
data[names=='Bob',3]=1
data

array([[ 1.40763989,  0.06948517, -1.27613851,  1.        ],
       [ 0.10380487,  0.21498122,  0.67072755,  0.77321209],
       [-0.59152043, -0.46612442, -0.18010961,  0.18551973],
       [ 0.17564053, -0.63889051, -0.38270991,  1.        ],
       [-1.46051822, -0.15296113, -0.85551065,  0.0689801 ],
       [-0.95997752,  0.16490724, -0.70213291, -0.12835829],
       [ 0.51764773, -1.65396676,  1.28771795,  1.04998571]])

In [49]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]
#Note: To combine multiple Boolean conditions,
#use arithmetic: & (for and) and | (for or)

array([[ 1.40763989,  0.06948517, -1.27613851,  1.        ],
       [-0.59152043, -0.46612442, -0.18010961,  0.18551973],
       [ 0.17564053, -0.63889051, -0.38270991,  1.        ],
       [-1.46051822, -0.15296113, -0.85551065,  0.0689801 ]])

In [50]:
data[data<0]=0   #to replace everything that is less than 0 = 0
data

array([[1.40763989, 0.06948517, 0.        , 1.        ],
       [0.10380487, 0.21498122, 0.67072755, 0.77321209],
       [0.        , 0.        , 0.        , 0.18551973],
       [0.17564053, 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 0.0689801 ],
       [0.        , 0.16490724, 0.        , 0.        ],
       [0.51764773, 0.        , 1.28771795, 1.04998571]])

In [51]:
arr=np.arange(15)  #15 INDX
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
arr=np.arange(15).reshape((3,5))  #3 row, 5 column
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
arr.T   # 5x3

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [54]:
np.dot(arr.T , arr)
#arr.T x arr  = (5x3)  x  (3x5)  =>  5x5
#make sure tengah tu sama number
# result = 1st row x 1st column, 2nd row x 2nd column

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [55]:
np.dot(arr , arr.T)
#arr.T x arr  = (3x5)  x  (5x3)  =>  3x3
#make sure tengah tu sama number
# result = 1st row x 1st column, 2nd row x 2nd column

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [56]:
#ufunc = universal function

In [57]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [59]:
x=np.random.randn(8)
x

array([-0.1407144 , -0.55353994,  0.12489743, -0.45228244,  0.78553752,
       -1.56591999, -0.83751671,  1.04821938])

In [60]:
y=np.random.randn(8)
y

array([-2.01564939,  1.39943307, -0.09281953,  1.44005425,  0.53044477,
       -0.48011788,  0.25249674,  0.68010644])

In [61]:
np.maximum(x,y)

array([-0.1407144 ,  1.39943307,  0.12489743,  1.44005425,  0.78553752,
       -0.48011788,  0.25249674,  1.04821938])

In [62]:
np.subtract(x,y)

array([ 1.87493499, -1.95297301,  0.21771696, -1.8923367 ,  0.25509275,
       -1.08580211, -1.09001345,  0.36811294])

In [63]:
import numpy as np
arr=np.random.randn(5,4)
arr

array([[ 2.02803454,  1.86826275, -1.28694678, -1.12176783],
       [-0.59075985,  1.62128395, -1.66036248, -0.36520279],
       [-0.72600845,  0.39964116,  1.65938657,  0.56231833],
       [ 0.17517332,  1.47008699, -1.22434069,  0.03274801],
       [ 1.03400932, -0.4585225 ,  1.17363257,  0.92840042]])

In [64]:
arr.mean()

np.float64(0.2759533281729186)

In [65]:
arr.sum()

np.float64(5.519066563458372)

In [66]:
arr.mean(axis=0)   #mean per column

array([ 0.38408978,  0.98015047, -0.26772616,  0.00729923])

In [67]:
arr.mean(axis=1) #mean per row

array([ 0.37189567, -0.24876029,  0.4738344 ,  0.11341691,  0.66937995])

In [68]:
arr=np.random.randn(6)
arr

array([ 9.07766973e-01, -2.95352929e-01, -3.71800029e-03, -1.61346905e+00,
        1.24473391e+00,  1.25074041e-03])

In [69]:
arr.sort()
arr

array([-1.61346905e+00, -2.95352929e-01, -3.71800029e-03,  1.25074041e-03,
        9.07766973e-01,  1.24473391e+00])

In [70]:
arr=np.random.randn(5,3)
arr

array([[-1.21757194, -1.19758451,  0.24690441],
       [ 0.24084728, -0.53572138, -0.84145555],
       [-1.09053373,  0.30856604, -1.79502965],
       [ 0.77444476, -0.59153448,  0.41543674],
       [-0.49279881, -0.04603414, -0.85938415]])

In [71]:
arr.sort(0)  #1=sort by row, 0=sort by column
arr

array([[-1.21757194, -1.19758451, -1.79502965],
       [-1.09053373, -0.59153448, -0.85938415],
       [-0.49279881, -0.53572138, -0.84145555],
       [ 0.24084728, -0.04603414,  0.24690441],
       [ 0.77444476,  0.30856604,  0.41543674]])

In [72]:
arr.sort(1)  #1=sort by row, 0=sort by column
arr

array([[-1.79502965, -1.21757194, -1.19758451],
       [-1.09053373, -0.85938415, -0.59153448],
       [-0.84145555, -0.53572138, -0.49279881],
       [-0.04603414,  0.24084728,  0.24690441],
       [ 0.30856604,  0.41543674,  0.77444476]])

In [73]:
names=np.array(['Bob', 'Joe','Will','Bob','Will','Joe','Joe'])

In [74]:
np.unique(names)  #sorting consider unique value

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [75]:
#inverse matric only possible for square array
from numpy.linalg import inv
X = np.random.randn(5,5)
X

array([[-0.72002097,  0.40401237,  1.39094948, -0.67398844,  1.6631155 ],
       [-2.80493024,  0.74086554, -1.62033924,  1.13320323, -0.48629498],
       [ 0.25376303,  0.17940102,  2.22896309,  0.70084139, -0.35314636],
       [-0.4200138 ,  1.9043402 ,  1.76625095, -2.44786356, -0.91386894],
       [ 0.1840107 , -0.65271044,  0.60913521, -0.87836421,  2.09795068]])

In [76]:
mat = X.T.dot(X)   #sama maksud dengan np.dot(X.T,X)  multiply transpose
inv(mat)  #inverse matrix

array([[ 4.06171698,  7.89512009, -1.81099459,  3.05866677,  3.27590298],
       [ 7.89512009, 15.85209906, -3.5682748 ,  6.14117405,  6.58773023],
       [-1.81099459, -3.5682748 ,  0.92553242, -1.30802985, -1.49483202],
       [ 3.05866677,  6.14117405, -1.30802985,  2.54257255,  2.56433818],
       [ 3.27590298,  6.58773023, -1.49483202,  2.56433818,  2.86282942]])

In [39]:
samples = np.random.normal(size=(4,4))
samples

array([[-1.28669456,  0.64762024, -1.3395669 , -0.40623574],
       [ 0.78416141,  0.10550051, -0.65175081,  1.41890776],
       [-2.15757062, -0.98069475,  0.31242533, -0.00745494],
       [ 1.61675036,  0.70820054, -0.09834619, -1.12435366]])